//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySpeedyMortgages
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int id { get; set; }
        public string x_sender { get; set; }
        public string x_receiver { get; set; }
        public string to_address { get; set; }
        public string from_address { get; set; }
        public Nullable<System.DateTime> dt_sent { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string sender_ip { get; set; }
    }
}
