//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySpeedyMortgages
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentItem
    {
        public int id { get; set; }
        public Nullable<bool> is_self_employed { get; set; }
        public Nullable<int> address_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<bool> is_currently_employed_here { get; set; }
        public byte[] position_title_type { get; set; }
        public Nullable<int> years_in_line_of_work { get; set; }
        public string name { get; set; }
    }
}
