//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySpeedyMortgages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Officer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Officer()
        {
            this.Officers_PhoneNumbers = new HashSet<Officers_PhoneNumbers>();
        }
    
        public int id { get; set; }
        public string officer_name { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<int> sort_order { get; set; }
        public bool is_visible { get; set; }
        public string biography { get; set; }
        public string biography_title { get; set; }
        public string officer_key { get; set; }
        public string nmls_number { get; set; }
        public string email_address { get; set; }
        public string mailing_address { get; set; }
        public Nullable<int> primary_phone_number_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Officers_PhoneNumbers> Officers_PhoneNumbers { get; set; }
    }
}
