//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySpeedyMortgages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Officers_PhoneNumbers
    {
        public int officer_id { get; set; }
        public int phone_number_id { get; set; }
        public int sort_number { get; set; }
        public bool is_visible { get; set; }
        public int id { get; set; }
    
        public virtual Officer Officer { get; set; }
        public virtual PhoneNumber PhoneNumber { get; set; }
    }
}
