//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySpeedyMortgages
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_initial_borrower_info
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public int loan_amount { get; set; }
        public int property_value { get; set; }
        public string loan_description { get; set; }
        public string quality_description { get; set; }
        public string officer_name { get; set; }
        public string created_dt_display { get; set; }
    }
}
